name: Update Stock Prices & Notifications

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7,13,20 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # הרשאת כתיבה קריטית המאפשרת לסקריפט לבצע Push חזרה לגיטהאב
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run update script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python update_data.py
